name: manual task

permissions:
  contents: read
  pull-requests: write

on: workflow_dispatch

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: START
        run: echo "Compiling the code..."
      - uses: actions/checkout@v3
      - name: RUN
        run: |
          npm i @actions/github -P
          ls
          pwd
          node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: END
        run: echo "Compile complete."